insert into products_shop.categories (name) values ('Ornamental Railings');
insert into products_shop.categories (name) values ('Plumbing & Medical Gas');
insert into products_shop.categories (name) values ('Termite Control');
insert into products_shop.categories (name) values ('Framing (Wood)');
insert into products_shop.categories (name) values ('Masonry & Precast');
insert into products_shop.categories (name) values ('Granite Surfaces');
insert into products_shop.categories (name) values ('Waterproofing & Caulking');
insert into products_shop.categories (name) values ('Drilled Shafts');
insert into products_shop.categories (name) values ('Soft Flooring and Base');
insert into products_shop.categories (name) values ('Roofing (Metal)');

insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Exc correct bunionette', 87.4, 1);
insert into products_shop.products (name, description, cost, category) values ('Consumer Durables', 'Simpl aspir lens extract', 60.78, 5);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Truncal vagotomy', 44.76, 10);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Scrotal les destruction', 31.11, 1);
insert into products_shop.products (name, description, cost, category) values ('Finance', 'Revis/reinsert ocul imp', 10.57, 5);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Finger amputation', 98.47, 6);
insert into products_shop.products (name, description, cost, category) values ('Transportation', 'Pharyngoscopy', 71.36, 3);
insert into products_shop.products (name, description, cost, category) values ('Public Utilities', 'Cell block/pap-blood', 92.16, 3);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Hip synovectomy', 40.89, 6);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Cl fx reduc-finger', 42.61, 1);
insert into products_shop.products (name, description, cost, category) values ('Capital Goods', 'Occlude abd artery NEC', 11.66, 5);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'IVUS extracran cereb ves', 85.89, 6);
insert into products_shop.products (name, description, cost, category) values ('Technology', 'Repair of gastroschisis', 66.7, 9);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Conization of cervix', 64.55, 3);
insert into products_shop.products (name, description, cost, category) values ('Energy', 'Non-invasive bone stimul', 82.92, 6);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Adm neuroprotective agnt', 55.99, 9);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'TRAM flap, free', 40.38, 3);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Bursectomy of hand', 30.59, 2);
insert into products_shop.products (name, description, cost, category) values ('Miscellaneous', 'Percutan facet denervat', 69.12, 5);
insert into products_shop.products (name, description, cost, category) values ('Basic Industries', 'Other hernia repair', 7.86, 1);
insert into products_shop.products (name, description, cost, category) values ('Miscellaneous', 'Inj therap subst periton', 92.69, 8);
insert into products_shop.products (name, description, cost, category) values ('Miscellaneous', 'Dermal regener graft', 66.59, 2);
insert into products_shop.products (name, description, cost, category) values ('Finance', 'Cervical cyst marsupial', 20.46, 2);
insert into products_shop.products (name, description, cost, category) values ('Consumer Non-Durables', 'Facial bone incision NEC', 41.68, 1);
insert into products_shop.products (name, description, cost, category) values ('Technology', 'Insert infusion pump', 55.95, 10);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Extended ophthal work-up', 64.58, 7);
insert into products_shop.products (name, description, cost, category) values ('Energy', 'Bilat reduct mammoplasty', 17.11, 8);
insert into products_shop.products (name, description, cost, category) values ('Consumer Services', 'Eye/orbit inj repair NEC', 32.76, 8);
insert into products_shop.products (name, description, cost, category) values ('Finance', 'Labial frenotomy', 82.82, 9);
insert into products_shop.products (name, description, cost, category) values ('Finance', 'Remov pros mat post seg', 1.82, 10);
insert into products_shop.products (name, description, cost, category) values ('Technology', 'Extracran-intracr bypass', 51.6, 8);
insert into products_shop.products (name, description, cost, category) values ('Capital Goods', 'Suture bladder lacerat', 59.03, 6);
insert into products_shop.products (name, description, cost, category) values ('Energy', 'Excision vaginal lesion', 58.62, 8);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Cisternal puncture', 89.73, 5);
insert into products_shop.products (name, description, cost, category) values ('Technology', 'Aorta-subclv-carot bypas', 33.41, 4);
insert into products_shop.products (name, description, cost, category) values ('Health Care', 'Other plastic ops fascia', 30.73, 6);
insert into products_shop.products (name, description, cost, category) values ('Finance', 'Replace ureteral stimul', 76.66, 1);