-- Данные с сайта https://mockaroo.com/
insert into products_shop.products (name, description, cost) values ('Tea - Herbal Sweet Dreams', 'Puncture wound with foreign body of left lesser toe(s) with damage to nail, initial encounter', 5.29);
insert into products_shop.products (name, description, cost) values ('Vinegar - Red Wine', 'Dislocation of metacarpal (bone), proximal end of unspecified hand, subsequent encounter', 58.75);
insert into products_shop.products (name, description, cost) values ('Beef - Salted', 'Displaced fracture of lateral condyle of left femur, initial encounter for open fracture type I or II', 62.04);
insert into products_shop.products (name, description, cost) values ('Stock - Veal, Brown', 'Unspecified injury of peroneal artery, right leg, initial encounter', 97.63);
insert into products_shop.products (name, description, cost) values ('Sugar - Brown, Individual', 'Penetrating wound without foreign body of left eyeball, subsequent encounter', 56.63);
insert into products_shop.products (name, description, cost) values ('Bar Nature Valley', 'Nondisplaced fracture of anterior wall of unspecified acetabulum, initial encounter for closed fracture', 99.86);
insert into products_shop.products (name, description, cost) values ('Soup - Campbells Tomato Ravioli', 'Displaced fracture of trapezoid [smaller multangular], right wrist, initial encounter for open fracture', 92.57);
insert into products_shop.products (name, description, cost) values ('Tea - Herbal Sweet Dreams', 'Corrosion of unspecified degree of left thumb (nail), initial encounter', 33.58);
insert into products_shop.products (name, description, cost) values ('Pepper - Paprika, Spanish', 'Nondisplaced avulsion fracture of unspecified ischium, initial encounter for open fracture', 45.81);
insert into products_shop.products (name, description, cost) values ('Bagelers - Cinn / Brown', 'Displaced comminuted fracture of shaft of ulna, right arm, subsequent encounter for open fracture type I or II with delayed healing', 47.98);
insert into products_shop.products (name, description, cost) values ('Glaze - Clear', 'Passenger on bus injured in collision with unspecified motor vehicles in traffic accident', 75.06);
insert into products_shop.products (name, description, cost) values ('Potatoes - Instant, Mashed', 'Unspecified ovarian cyst, unspecified side', 47.1);
insert into products_shop.products (name, description, cost) values ('Noodles - Steamed Chow Mein', 'Nondisplaced fracture of neck of unspecified talus, initial encounter for closed fracture', 51.27);
insert into products_shop.products (name, description, cost) values ('Red Snapper - Fillet, Skin On', 'Carcinoma in situ of skin of left upper limb, including shoulder', 34.59);
insert into products_shop.products (name, description, cost) values ('Compound - Rum', 'Other fracture of shaft of right tibia, subsequent encounter for open fracture type I or II with delayed healing', 24.91);
insert into products_shop.products (name, description, cost) values ('Cheese - Comtomme', 'Unspecified subluxation of left little finger, sequela', 93.24);
insert into products_shop.products (name, description, cost) values ('Syrup - Monin - Granny Smith', 'Unspecified injury of unspecified blood vessel at wrist and hand level of left arm, initial encounter', 97.21);
insert into products_shop.products (name, description, cost) values ('Bacon Strip Precooked', 'Other contact with crocodile, initial encounter', 39.51);
insert into products_shop.products (name, description, cost) values ('Flour - All Purpose', 'Nondisplaced midcervical fracture of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 40.61);
insert into products_shop.products (name, description, cost) values ('Butter Balls Salted', 'Subluxation of metacarpal (bone), proximal end of unspecified hand, sequela', 78.14);
insert into products_shop.products (name, description, cost) values ('Plaintain', 'Corrosion of second degree of right toe(s) (nail), sequela', 95.31);
insert into products_shop.products (name, description, cost) values ('Beans - Fava, Canned', 'Stem cells transplant status', 26.05);
insert into products_shop.products (name, description, cost) values ('Soup - Campbells Chicken', 'Salter-Harris Type I physeal fracture of lower end of right fibula', 5.21);
insert into products_shop.products (name, description, cost) values ('Knife Plastic - White', 'Breakdown (mechanical) of other cardiac electronic device', 38.36);
insert into products_shop.products (name, description, cost) values ('Tortillas - Flour, 8', 'Deletion from autosomes, unspecified', 99.6);
insert into products_shop.products (name, description, cost) values ('Soup Campbells Mexicali Tortilla', 'Poisoning by other fibrinolysis-affecting drugs, accidental (unintentional)', 23.7);
insert into products_shop.products (name, description, cost) values ('Gingerale - Diet - Schweppes', 'Unspecified fracture of shaft of left tibia, initial encounter for open fracture type IIIA, IIIB, or IIIC', 67.38);
insert into products_shop.products (name, description, cost) values ('Gatorade - Orange', 'Unspecified injury of unspecified muscle and tendon at lower leg level', 58.77);
insert into products_shop.products (name, description, cost) values ('Soup - Canadian Pea, Dry Mix', 'Helicopter collision injuring occupant, sequela', 70.3);
insert into products_shop.products (name, description, cost) values ('Green Tea Refresher', 'Contusion of other part of colon, sequela', 48.48);
insert into products_shop.products (name, description, cost) values ('Shopper Bag - S - 4', 'Cystostomy infection', 94.73);
insert into products_shop.products (name, description, cost) values ('Veal - Shank, Pieces', 'Nondisplaced fracture of anterior process of unspecified calcaneus, sequela', 57.3);
insert into products_shop.products (name, description, cost) values ('Sparkling Wine - Rose, Freixenet', 'Synovial hypertrophy, not elsewhere classified, right lower leg', 2.05);
insert into products_shop.products (name, description, cost) values ('Lemonade - Pineapple Passion', 'Unspecified physeal fracture of right calcaneus, subsequent encounter for fracture with nonunion', 87.89);
insert into products_shop.products (name, description, cost) values ('Cleaner - Pine Sol', 'Attention and concentration deficit following nontraumatic subarachnoid hemorrhage', 78.48);
insert into products_shop.products (name, description, cost) values ('Compound - Mocha', 'Unspecified occupant of heavy transport vehicle injured in collision with other motor vehicles in nontraffic accident', 90.79);
insert into products_shop.products (name, description, cost) values ('Flour - Whole Wheat', 'Burn of second degree of multiple sites of wrist and hand', 21.96);
insert into products_shop.products (name, description, cost) values ('Pants Custom Dry Clean', 'External constriction of right eyelid and periocular area', 15.26);
insert into products_shop.products (name, description, cost) values ('Appetizer - Chicken Satay', 'Unspecified physeal fracture of lower end of unspecified fibula, subsequent encounter for fracture with nonunion', 22.95);
insert into products_shop.products (name, description, cost) values ('Wine - Puligny Montrachet A.', 'Toxic effect of unspecified snake venom', 9.37);
insert into products_shop.products (name, description, cost) values ('Sauce - Sesame Thai Dressing', 'Intertrochanteric fracture of femur', 40.6);
insert into products_shop.products (name, description, cost) values ('Sauce Tomato Pouch', 'Burn of unspecified degree of unspecified site of right lower limb, except ankle and foot, sequela', 82.48);
insert into products_shop.products (name, description, cost) values ('Yogurt - Blueberry, 175 Gr', 'Birth injury to facial nerve', 31.99);
insert into products_shop.products (name, description, cost) values ('Beer - Tetleys', 'Other mechanical complication of internal fixation device of bone of right lower leg', 0.55);
insert into products_shop.products (name, description, cost) values ('Eggplant - Asian', 'Cellulitis of right toe', 42.65);
insert into products_shop.products (name, description, cost) values ('Flavouring - Orange', 'Breakdown (mechanical) of internal fixation device of bone of left forearm, initial encounter', 33.89);
insert into products_shop.products (name, description, cost) values ('Pail With Metal Handle 16l White', 'Unspecified car occupant injured in collision with heavy transport vehicle or bus in traffic accident', 63.02);
insert into products_shop.products (name, description, cost) values ('Creme De Banane - Marie', 'Other displaced fracture of upper end of right humerus, sequela', 7.96);
insert into products_shop.products (name, description, cost) values ('Ocean Spray - Ruby Red', 'Open bite of unspecified breast, subsequent encounter', 67.16);
insert into products_shop.products (name, description, cost) values ('Contreau', 'Injury of other nerves at hip and thigh level, right leg', 90.4);
